# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    echo Hello, world!
    ifconfig
    hostname
    pwd
    ls -l
  displayName: 'Script 1'

- script: |
    echo Hello, world!
    ifconfig
    hostname
    pwd
    ls -l
    cd
    ls -l
  displayName: 'Script 2'

- script: |
    echo Hello, world!
    ifconfig
    hostname
    pwd
    ls -l
    echo $(Build.BinariesDirectory)
    echo $(Build.ArtifactStagingDirectory)
  displayName: 'Script 3'


- task: UseNode@1
  inputs:
    version: '10.14'

- task: Npm@1
  inputs:
    command: 'install'
  - script: |
      echo hello
    display name: 'hi'





- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/node.zip'
    replaceExistingArchive: true

- script: |
    echo ls
    ls -l
    pwd
  displayName: 'Check archive'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- script: |
    echo ls
    ls -l
    pwd
  displayName: 'Check publish'